jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create .env file
        run: |
          cp .env.example .env
          cat <<EOT >> .env
          APP_KEY=${{ secrets.APP_KEY }}
          DB_HOST=${{ secrets.MYSQL_HOST }}
          DB_DATABASE=${{ secrets.MYSQL_DATABASE }}
          DB_USERNAME=${{ secrets.MYSQL_USER }}
          DB_PASSWORD=${{ secrets.MYSQL_PASSWORD }}
          EOT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t my-laravel-app:latest .

      - name: Set version
        id: vars
        run: |
          echo "VERSION=$(date +'%Y%m%d%H%M')" >> $GITHUB_ENV

      - name: Print Docker username and version
        run: |
          echo "Docker Username: ${{ secrets.DOCKER_USERNAME }}"
          echo "Version: ${{ env.VERSION }}"

      - name: List Docker images
        run: docker images

      - name: Tag Docker image
        run: |
          docker tag my-laravel-app:latest ${{ secrets.DOCKER_USERNAME }}/my-laravel-app:${{ env.VERSION }}

      - name: Push Docker image to DockerHub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/my-laravel-app:${{ env.VERSION }}
